metadata.format.version = "1.1"

[versions]

minestom = "7b8445d0e2"

# Terminal / Logging
tinylog = "2.4.1"
jline = "3.21.0"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"

[libraries]

minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

# Logging
tinylog-api = { group = "org.tinylog", name = "tinylog-api", version.ref = "tinylog" }
tinylog-impl = { group = "org.tinylog", name = "tinylog-impl", version.ref = "tinylog" }

# Terminal
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jline-jansi = { group = "org.jline", name = "jline-terminal-jansi", version.ref = "jline" }

[bundles]

logging = ["tinylog-api", "tinylog-impl"]
terminal = ["jline", "jline-jansi"]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
